package se.minekonomi.app;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
    private final int BG=Color.rgb(10,18,27),SURFACE=Color.rgb(20,31,42),CARD=Color.rgb(27,40,53),CARD2=Color.rgb(34,49,63),TEXT=Color.WHITE,MUTED=Color.rgb(166,180,193),ACCENT=Color.rgb(71,200,134),RED=Color.rgb(255,108,117);
    private SharedPreferences prefs; private LinearLayout content; private int monthOffset=0;
    private final NumberFormat money=NumberFormat.getCurrencyInstance(new Locale("sv","SE"));
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("min_ekonomi",MODE_PRIVATE);ensureDefaults();ensureFixedForCurrentMonth();showOverview();}
    private int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} private TextView tv(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextColor(TEXT);v.setTextSize(sp);v.setTypeface(null,bold?Typeface.BOLD:Typeface.NORMAL);return v;} private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} private String fmt(double v){return money.format(v).replace(" "," ");} private double parse(EditText e){try{return Double.parseDouble(e.getText().toString().trim().replace(',','.'));}catch(Exception x){return 0;}}
    private JSONArray arr(String k){try{return new JSONArray(prefs.getString(k,"[]"));}catch(Exception e){return new JSONArray();}} private void save(String k,JSONArray a){prefs.edit().putString(k,a.toString()).apply();}
    private Calendar calForOffset(){Calendar c=Calendar.getInstance();c.add(Calendar.MONTH,monthOffset);return c;} private String selectedKey(){return new SimpleDateFormat("yyyy-MM",Locale.getDefault()).format(calForOffset().getTime());} private String selectedTitle(){String s=new SimpleDateFormat("MMMM yyyy",new Locale("sv","SE")).format(calForOffset().getTime());return s.substring(0,1).toUpperCase(new Locale("sv","SE"))+s.substring(1);} private String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).format(new Date());}
    private TextView action(String s){TextView b=tv(s,15,true);b.setGravity(Gravity.CENTER);b.setPadding(dp(14),dp(14),dp(14),dp(14));b.setBackground(bg(ACCENT,18));b.setTextColor(Color.rgb(5,28,20));b.setClickable(true);return b;} private TextView smallAction(String s,int c){TextView b=tv(s,13,true);b.setGravity(Gravity.CENTER);b.setPadding(dp(10),dp(10),dp(10),dp(10));b.setBackground(bg(c,14));b.setClickable(true);return b;}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(bg(CARD,22));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));c.setLayoutParams(p);return c;} private void section(String s){TextView h=tv(s,20,true);h.setPadding(dp(2),dp(12),0,dp(9));content.addView(h);} private void emptyCompact(String s){TextView e=tv(s,14,false);e.setTextColor(MUTED);e.setGravity(Gravity.CENTER);e.setPadding(dp(8),dp(10),dp(8),dp(12));content.addView(e);}
    private void shell(String title,int selected){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(20),dp(26),dp(20),dp(8));head.addView(tv(title,29,true));if(selected==0){LinearLayout mr=new LinearLayout(this);mr.setGravity(Gravity.CENTER_VERTICAL);TextView prev=smallAction("‹",Color.rgb(38,54,68)),next=smallAction("›",Color.rgb(38,54,68));TextView mt=tv(selectedTitle(),15,false);mt.setTextColor(MUTED);mt.setGravity(Gravity.CENTER);prev.setOnClickListener(v->{monthOffset--;showOverview();});next.setOnClickListener(v->{monthOffset++;showOverview();});mr.addView(prev,new LinearLayout.LayoutParams(dp(44),dp(40)));mr.addView(mt,new LinearLayout.LayoutParams(0,dp(40),1));mr.addView(next,new LinearLayout.LayoutParams(dp(44),dp(40)));head.addView(mr);}root.addView(head);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(8),dp(16),dp(24));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));root.addView(bottomNav(selected),new LinearLayout.LayoutParams(-1,dp(72)));setContentView(root);}
    private View bottomNav(int selected){LinearLayout n=new LinearLayout(this);n.setBackgroundColor(SURFACE);n.setPadding(dp(5),dp(5),dp(5),dp(7));String[] ic={"⌂","↕","◎","▤","▥"},la={"Översikt","Poster","Budget","Räkningar","Statistik"};View.OnClickListener[] ls={v->showOverview(),v->showTransactions(),v->showBudget(),v->showBills(),v->showStats()};for(int i=0;i<la.length;i++){LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.setGravity(Gravity.CENTER);if(i==selected)t.setBackground(bg(Color.rgb(34,61,56),16));TextView a=tv(ic[i],22,true),b=tv(la[i],10,i==selected);a.setGravity(Gravity.CENTER);b.setGravity(Gravity.CENTER);a.setTextColor(i==selected?ACCENT:MUTED);b.setTextColor(i==selected?ACCENT:MUTED);t.addView(a);t.addView(b);t.setOnClickListener(ls[i]);n.addView(t,new LinearLayout.LayoutParams(0,-1,1));}return n;}
    private void ensureDefaults(){if(arr("accounts").length()==0){try{JSONArray a=new JSONArray();a.put(new JSONObject().put("name","Lönekonto").put("start",0));save("accounts",a);}catch(Exception ignored){}}}
    private void ensureFixedForCurrentMonth(){String key=new SimpleDateFormat("yyyy-MM",Locale.getDefault()).format(new Date());JSONArray fixed=arr("fixed"),tx=arr("tx");Set<String> done=new HashSet<>();for(int i=0;i<tx.length();i++)try{JSONObject o=tx.getJSONObject(i);if(key.equals(o.optString("month"))&&o.optBoolean("fromFixed"))done.add(o.optString("fixedId"));}catch(Exception ignored){}boolean ch=false;for(int i=0;i<fixed.length();i++)try{JSONObject f=fixed.getJSONObject(i);String id=f.optString("id");if(id.isEmpty()){id=UUID.randomUUID().toString();f.put("id",id);}if(!done.contains(id)){JSONObject o=new JSONObject();o.put("name",f.optString("name"));o.put("amount",f.optDouble("amount"));o.put("type",f.optString("type"));o.put("category",f.optString("category","Övrigt"));o.put("account",f.optString("account","Lönekonto"));o.put("date",key+"-01");o.put("month",key);o.put("fromFixed",true);o.put("fixedId",id);tx.put(o);ch=true;}}catch(Exception ignored){}if(ch){save("fixed",fixed);save("tx",tx);}}
    private double[] totals(String key){double in=0,out=0;JSONArray a=arr("tx");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);String d=o.optString("date");if(d.startsWith(key)){if("Inkomst".equals(o.optString("type")))in+=o.optDouble("amount");else out+=o.optDouble("amount");}}catch(Exception ignored){}return new double[]{in,out};}
    private void showOverview(){if(monthOffset==0)ensureFixedForCurrentMonth();shell("Min Ekonomi",0);String key=selectedKey();double[] t=totals(key);double left=t[0]-t[1];double budget=prefs.getFloat("budget",0);LinearLayout hero=card();hero.setBackground(bg(Color.rgb(25,54,49),26));hero.setPadding(dp(20),dp(20),dp(20),dp(18));TextView l=tv("Kvar denna månad",14,false);l.setTextColor(Color.rgb(184,216,207));hero.addView(l);TextView val=tv(fmt(left),34,true);val.setTextColor(left>=0?ACCENT:RED);val.setPadding(0,dp(5),0,dp(12));hero.addView(val);LinearLayout pair=new LinearLayout(this);pair.addView(metricMini("Inkomster",fmt(t[0]),ACCENT),new LinearLayout.LayoutParams(0,-2,1));pair.addView(metricMini("Utgifter",fmt(t[1]),RED),new LinearLayout.LayoutParams(0,-2,1));hero.addView(pair);if(budget>0){int pct=(int)Math.round(t[1]/budget*100);TextView b=tv("Budget • "+Math.min(999,pct)+" % använt • "+fmt(Math.max(0,budget-t[1]))+" kvar",12,false);b.setTextColor(MUTED);b.setPadding(0,dp(13),0,dp(6));hero.addView(b);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(100);p.setProgress(Math.min(100,pct));hero.addView(p,new LinearLayout.LayoutParams(-1,dp(7)));}content.addView(hero);TextView add=action("＋  Lägg till transaktion");add.setOnClickListener(v->transactionDialog(-1));content.addView(add);section("Kommande räkningar");addUpcomingBills();section("Senaste");JSONArray a=arr("tx");int shown=0;for(int i=a.length()-1;i>=0&&shown<4;i--)try{if(a.getJSONObject(i).optString("date").startsWith(key)){addTxRow(a,i,false);shown++;}}catch(Exception ignored){}if(shown==0)emptyCompact("Inga transaktioner den här månaden.");}
    private View metricMini(String s,String v,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);TextView a=tv(s,12,false),b=tv(v,17,true);a.setTextColor(MUTED);b.setTextColor(c);x.addView(a);x.addView(b);return x;}
    private void addUpcomingBills(){JSONArray a=arr("bills");int shown=0;for(int i=0;i<a.length()&&shown<3;i++)try{JSONObject o=a.getJSONObject(i);if(o.optBoolean("paid"))continue;LinearLayout c=card(),r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView n=tv(o.optString("name"),16,true),d=tv("Förfaller "+o.optString("due"),12,false);d.setTextColor(MUTED);tx.addView(n);tx.addView(d);r.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView am=tv(fmt(o.optDouble("amount")),16,true);am.setTextColor(RED);r.addView(am);c.addView(r);content.addView(c);shown++;}catch(Exception ignored){}if(shown==0)emptyCompact("Inga kommande räkningar.");}
    private void showTransactions(){shell("Poster",1);TextView add=action("＋  Ny transaktion");add.setOnClickListener(v->transactionDialog(-1));content.addView(add);LinearLayout quick=new LinearLayout(this);TextView acc=smallAction("Konton",Color.rgb(50,77,101)),fix=smallAction("Fasta belopp",Color.rgb(50,77,101));acc.setOnClickListener(v->showAccounts());fix.setOnClickListener(v->showFixed());quick.addView(acc,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams qlp=new LinearLayout.LayoutParams(0,-2,1);qlp.setMargins(dp(8),0,0,0);quick.addView(fix,qlp);LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(-1,-2);qp.setMargins(0,dp(10),0,0);content.addView(quick,qp);section("Alla poster");JSONArray a=arr("tx");if(a.length()==0)emptyCompact("Inga transaktioner ännu.");for(int i=a.length()-1;i>=0;i--)addTxRow(a,i,true);}
    private void addTxRow(JSONArray a,int i,boolean controls){try{JSONObject o=a.getJSONObject(i);LinearLayout c=card(),r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView icon=tv("Inkomst".equals(o.optString("type"))?"↑":"•",20,true);icon.setGravity(Gravity.CENTER);icon.setBackground(bg(CARD2,16));r.addView(icon,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(12),0,dp(8),0);TextView n=tv(o.optString("name"),16,true),s=tv(o.optString("category","Övrigt")+" • "+o.optString("account","Lönekonto")+" • "+o.optString("date"),12,false);s.setTextColor(MUTED);tx.addView(n);tx.addView(s);r.addView(tx,new LinearLayout.LayoutParams(0,-2,1));boolean inc="Inkomst".equals(o.optString("type"));TextView m=tv((inc?"+ ":"− ")+fmt(o.optDouble("amount")),16,true);m.setTextColor(inc?ACCENT:RED);r.addView(m);c.addView(r);if(controls&&!o.optBoolean("fromFixed")){LinearLayout aa=new LinearLayout(this);aa.setPadding(0,dp(10),0,0);TextView ed=smallAction("Redigera",Color.rgb(48,69,88)),del=smallAction("Ta bort",Color.rgb(92,48,54));final int idx=i;ed.setOnClickListener(v->transactionDialog(idx));del.setOnClickListener(v->deleteAt("tx",idx,()->showTransactions()));aa.addView(ed,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(8),0,0,0);aa.addView(del,lp);c.addView(aa);}content.addView(c);}catch(Exception ignored){}}
    private String[] accountNames(){JSONArray a=arr("accounts");if(a.length()==0)return new String[]{"Lönekonto"};String[] x=new String[a.length()];for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);x[i]=o==null?"Konto":o.optString("name","Konto");}return x;}
    private void transactionDialog(int idx){JSONArray all=arr("tx");JSONObject old=idx>=0?all.optJSONObject(idx):null;LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this),am=new EditText(this);n.setHint("Beskrivning");am.setHint("Belopp");am.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Utgift","Inkomst"}));Spinner cat=new Spinner(this);String[] cats={"Mat","Boende","Bil/transport","Abonnemang","Nöjen","Hälsa","Shopping","Lön","Övrigt"};cat.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,cats));Spinner acc=new Spinner(this);String[] ac=accountNames();acc.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ac));if(old!=null){n.setText(old.optString("name"));am.setText(String.valueOf(old.optDouble("amount")));type.setSelection("Inkomst".equals(old.optString("type"))?1:0);}b.addView(n);b.addView(am);b.addView(type);b.addView(cat);b.addView(acc);final JSONObject original=old;new AlertDialog.Builder(this).setTitle(idx>=0?"Redigera transaktion":"Ny transaktion").setView(b).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{if(n.getText().toString().trim().isEmpty()||parse(am)<=0)return;try{JSONObject o=new JSONObject();o.put("name",n.getText().toString().trim());o.put("amount",parse(am));o.put("type",type.getSelectedItem().toString());o.put("category",cat.getSelectedItem().toString());o.put("account",acc.getSelectedItem().toString());o.put("date",original!=null?original.optString("date",today()):today());JSONArray a=arr("tx");if(idx>=0){JSONArray y=new JSONArray();for(int i=0;i<a.length();i++)y.put(i==idx?o:a.getJSONObject(i));save("tx",y);}else{a.put(o);save("tx",a);}showTransactions();}catch(Exception ignored){}}).show();}
    private void showAccounts(){shell("Konton",1);TextView add=action("＋  Lägg till konto");add.setOnClickListener(v->accountDialog());content.addView(add);section("Mina konton");JSONArray a=arr("accounts");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);double bal=o.optDouble("start")+accountFlow(o.optString("name"));LinearLayout c=card();c.addView(tv(o.optString("name"),17,true));TextView b=tv("Saldo: "+fmt(bal),22,true);b.setTextColor(bal>=0?ACCENT:RED);c.addView(b);content.addView(c);}catch(Exception ignored){}}
    private double accountFlow(String name){double x=0;JSONArray a=arr("tx");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);if(name.equals(o.optString("account","Lönekonto")))x+=("Inkomst".equals(o.optString("type"))?1:-1)*o.optDouble("amount");}catch(Exception ignored){}return x;}
    private void accountDialog(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this),s=new EditText(this);n.setHint("Kontonamn");s.setHint("Startsaldo");s.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED);b.addView(n);b.addView(s);new AlertDialog.Builder(this).setTitle("Nytt konto").setView(b).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{if(n.getText().toString().trim().isEmpty())return;try{JSONArray a=arr("accounts");a.put(new JSONObject().put("name",n.getText().toString().trim()).put("start",parse(s)));save("accounts",a);showAccounts();}catch(Exception ignored){}}).show();}
    private void showFixed(){shell("Fasta belopp",1);TextView add=action("＋  Lägg till fast belopp");add.setOnClickListener(v->fixedDialog());content.addView(add);JSONArray a=arr("fixed");if(a.length()==0)emptyCompact("Inga fasta månadsbelopp ännu.");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);LinearLayout c=card();c.addView(tv(o.optString("name"),17,true));TextView s=tv(o.optString("type")+" • "+fmt(o.optDouble("amount"))+" • "+o.optString("account","Lönekonto"),13,false);s.setTextColor(MUTED);c.addView(s);final int idx=i;TextView del=smallAction("Ta bort",Color.rgb(92,48,54));del.setOnClickListener(v->deleteAt("fixed",idx,()->showFixed()));c.addView(del);content.addView(c);}catch(Exception ignored){}}
    private void fixedDialog(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this),am=new EditText(this);n.setHint("Namn");am.setHint("Belopp");am.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Utgift","Inkomst"}));Spinner acc=new Spinner(this);acc.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,accountNames()));b.addView(n);b.addView(am);b.addView(type);b.addView(acc);new AlertDialog.Builder(this).setTitle("Fast månadsbelopp").setView(b).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{if(n.getText().toString().trim().isEmpty()||parse(am)<=0)return;try{JSONArray a=arr("fixed");a.put(new JSONObject().put("id",UUID.randomUUID().toString()).put("name",n.getText().toString().trim()).put("amount",parse(am)).put("type",type.getSelectedItem().toString()).put("category","Övrigt").put("account",acc.getSelectedItem().toString()));save("fixed",a);ensureFixedForCurrentMonth();showFixed();}catch(Exception ignored){}}).show();}
    private void showBudget(){shell("Budget & sparmål",2);String key=new SimpleDateFormat("yyyy-MM",Locale.getDefault()).format(new Date());double budget=prefs.getFloat("budget",0),spent=totals(key)[1];LinearLayout c=card();c.addView(tv("Månadsbudget",14,false));TextView v=tv(fmt(budget),26,true);v.setTextColor(ACCENT);c.addView(v);TextView sub=tv("Förbrukat "+fmt(spent)+" • Kvar "+fmt(Math.max(0,budget-spent)),13,false);sub.setTextColor(MUTED);c.addView(sub);content.addView(c);TextView e=action("Ändra månadsbudget");e.setOnClickListener(x->budgetDialog());content.addView(e);section("Sparmål");TextView add=smallAction("＋ Nytt sparmål",Color.rgb(50,77,101));add.setOnClickListener(x->goalDialog());content.addView(add);JSONArray g=arr("goals");if(g.length()==0)emptyCompact("Inga sparmål ännu.");for(int i=0;i<g.length();i++)try{JSONObject o=g.getJSONObject(i);LinearLayout gc=card();gc.addView(tv(o.optString("name"),17,true));double cur=o.optDouble("saved"),target=o.optDouble("target");TextView st=tv(fmt(cur)+" av "+fmt(target),14,false);st.setTextColor(MUTED);gc.addView(st);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(100);p.setProgress(target>0?(int)Math.min(100,cur/target*100):0);gc.addView(p,new LinearLayout.LayoutParams(-1,dp(7)));final int idx=i;TextView plus=smallAction("Lägg till sparande",Color.rgb(48,69,88));plus.setOnClickListener(x->addToGoal(idx));gc.addView(plus);content.addView(gc);}catch(Exception ignored){}}
    private void budgetDialog(){EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setText(String.valueOf(prefs.getFloat("budget",0)));new AlertDialog.Builder(this).setTitle("Månadsbudget").setView(e).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{prefs.edit().putFloat("budget",(float)parse(e)).apply();showBudget();}).show();}
    private void goalDialog(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this),t=new EditText(this);n.setHint("Sparmål, t.ex. Semester");t.setHint("Målbelopp");t.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);b.addView(n);b.addView(t);new AlertDialog.Builder(this).setTitle("Nytt sparmål").setView(b).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{if(n.getText().toString().trim().isEmpty()||parse(t)<=0)return;try{JSONArray g=arr("goals");g.put(new JSONObject().put("name",n.getText().toString().trim()).put("target",parse(t)).put("saved",0));save("goals",g);showBudget();}catch(Exception ignored){}}).show();}
    private void addToGoal(int idx){EditText e=new EditText(this);e.setHint("Belopp");e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);new AlertDialog.Builder(this).setTitle("Lägg till sparande").setView(e).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{try{JSONArray g=arr("goals");JSONObject o=g.getJSONObject(idx);o.put("saved",o.optDouble("saved")+parse(e));save("goals",g);showBudget();}catch(Exception ignored){}}).show();}
    private void showBills(){shell("Räkningar",3);TextView add=action("＋  Lägg till räkning");add.setOnClickListener(v->billDialog());content.addView(add);JSONArray a=arr("bills");if(a.length()==0)emptyCompact("Inga räkningar ännu.");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);LinearLayout c=card();c.addView(tv(o.optString("name"),17,true));TextView s=tv((o.optBoolean("paid")?"Betald":"Förfaller "+o.optString("due"))+" • "+fmt(o.optDouble("amount")),13,false);s.setTextColor(o.optBoolean("paid")?ACCENT:MUTED);c.addView(s);if(!o.optBoolean("paid")){final int idx=i;TextView pay=smallAction("Markera betald",Color.rgb(34,91,67));pay.setOnClickListener(v->payBill(idx));c.addView(pay);}content.addView(c);}catch(Exception ignored){}}
    private void billDialog(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this),am=new EditText(this),due=new EditText(this);n.setHint("Räkning");am.setHint("Belopp");am.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);due.setHint("Förfallodatum YYYY-MM-DD");b.addView(n);b.addView(am);b.addView(due);new AlertDialog.Builder(this).setTitle("Ny räkning").setView(b).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{if(n.getText().toString().trim().isEmpty()||parse(am)<=0)return;try{JSONArray a=arr("bills");a.put(new JSONObject().put("name",n.getText().toString().trim()).put("amount",parse(am)).put("due",due.getText().toString().trim()).put("paid",false));save("bills",a);showBills();}catch(Exception ignored){}}).show();}
    private void payBill(int idx){try{JSONArray b=arr("bills");JSONObject bill=b.getJSONObject(idx);bill.put("paid",true);bill.put("paidDate",today());save("bills",b);JSONArray tx=arr("tx");tx.put(new JSONObject().put("name",bill.optString("name")).put("amount",bill.optDouble("amount")).put("type","Utgift").put("category","Räkning").put("account","Lönekonto").put("date",today()));save("tx",tx);showBills();}catch(Exception ignored){}}
    private void showStats(){shell("Statistik",4);section("Senaste 6 månaderna");Calendar c=Calendar.getInstance();double max=1;double[][] vals=new double[6][2];String[] labels=new String[6];for(int i=5;i>=0;i--){String key=new SimpleDateFormat("yyyy-MM",Locale.getDefault()).format(c.getTime());vals[i]=totals(key);labels[i]=new SimpleDateFormat("MMM yy",new Locale("sv","SE")).format(c.getTime());max=Math.max(max,vals[i][1]);c.add(Calendar.MONTH,-1);}for(int i=0;i<6;i++){LinearLayout cc=card();cc.addView(tv(labels[i],16,true));TextView line=tv("In "+fmt(vals[i][0])+"   •   Ut "+fmt(vals[i][1]),13,false);line.setTextColor(MUTED);cc.addView(line);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(1000);p.setProgress((int)(vals[i][1]/max*1000));cc.addView(p,new LinearLayout.LayoutParams(-1,dp(7)));content.addView(cc);}section("Utgifter per kategori denna månad");Map<String,Double> m=new LinkedHashMap<>();String key=new SimpleDateFormat("yyyy-MM",Locale.getDefault()).format(new Date());JSONArray tx=arr("tx");for(int i=0;i<tx.length();i++)try{JSONObject o=tx.getJSONObject(i);if(o.optString("date").startsWith(key)&&"Utgift".equals(o.optString("type")))m.put(o.optString("category","Övrigt"),m.getOrDefault(o.optString("category","Övrigt"),0.0)+o.optDouble("amount"));}catch(Exception ignored){}if(m.isEmpty())emptyCompact("Ingen statistik ännu.");for(Map.Entry<String,Double> e:m.entrySet()){LinearLayout cc=card(),r=new LinearLayout(this);r.addView(tv(e.getKey(),15,true),new LinearLayout.LayoutParams(0,-2,1));TextView v=tv(fmt(e.getValue()),15,true);v.setTextColor(RED);r.addView(v);cc.addView(r);content.addView(cc);}}
    private interface Done{void run();} private void deleteAt(String key,int idx,Done done){new AlertDialog.Builder(this).setTitle("Ta bort?").setNegativeButton("Avbryt",null).setPositiveButton("Ta bort",(d,w)->{JSONArray a=arr(key),b=new JSONArray();for(int i=0;i<a.length();i++)if(i!=idx)try{b.put(a.get(i));}catch(Exception ignored){}save(key,b);done.run();}).show();}
}
