from pathlib import Path
p=Path('app/src/main/java/se/minekonomi/app/MainActivity.java')
lines=p.read_text(encoding='utf-8').splitlines()

def repl_prefix(prefix,new):
    for i,l in enumerate(lines):
        if l.startswith(prefix):
            lines[i]=new
            return
    raise SystemExit('missing '+prefix)

repl_prefix('  void showPlannedPurchases(){', '''  void showPlannedPurchases(){shell("Planerade köp",2);TextView add=action("＋ Nytt planerat köp");add.setOnClickListener(v->plannedDialogV191(-1));content.addView(add);section("Planerade");JSONArray a=arr("planned");if(a.length()==0){empty("Inga planerade köp ännu.");return;}double[] mt=totals(monthKey(Calendar.getInstance()));double base=mt[0]-mt[1]-unpaidBills(monthKey(Calendar.getInstance()))-plannedSavings();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;final int ix=i;double amount=o.optDouble("amount");LinearLayout c=card();TextView n=tv(o.optString("name","Planerat köp"),18,true);c.addView(n);TextView am=tv(fmt(amount),22,true);am.setTextColor(AMBER);c.addView(am);double after=base-amount;TextView impact=tv("Fritt kvar efter köpet: "+fmt(after),13,false);impact.setTextColor(after>=0?ACCENT:RED);c.addView(impact);String acc=o.optString("account",accountNames().length>0?accountNames()[0]:"Lönekonto");String cat=o.optString("category","Övrigt");TextView meta=tv(cat+" • "+acc,12,false);meta.setTextColor(MUTED);c.addView(meta);LinearLayout row=new LinearLayout(this);TextView edit=small("✏ Redigera",Color.rgb(50,77,101));TextView del=small("🗑 Ta bort",Color.rgb(90,48,55));edit.setOnClickListener(v->plannedDialogV191(ix));del.setOnClickListener(v->deletePlannedV191(ix));row.addView(edit,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams dlp=new LinearLayout.LayoutParams(0,-2,1);dlp.setMargins(dp(8),0,0,0);row.addView(del,dlp);c.addView(row);TextView done=small("✓ Markera som genomfört",Color.rgb(35,89,65));done.setOnClickListener(v->completePlannedV191(ix));c.addView(done);content.addView(c);}}''')

insert=len(lines)-1
extra='''  void plannedDialogV191(int ix){JSONArray a=arr("planned");JSONObject old=ix>=0?a.optJSONObject(ix):null;LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(14),0,dp(14),0);EditText n=new EditText(this),am=new EditText(this);n.setHint("Vad vill du köpa?");am.setHint("Belopp");am.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);Spinner cat=new Spinner(this),acc=new Spinner(this);cat.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,CATS));String[] ac=accountNames();acc.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ac));if(old!=null){n.setText(old.optString("name"));am.setText(String.valueOf(old.optDouble("amount")));for(int i=0;i<CATS.length;i++)if(CATS[i].equals(old.optString("category","Övrigt")))cat.setSelection(i);for(int i=0;i<ac.length;i++)if(ac[i].equals(old.optString("account",ac.length>0?ac[0]:"")))acc.setSelection(i);}b.addView(n);b.addView(am);b.addView(cat);b.addView(acc);new AlertDialog.Builder(this).setTitle(ix>=0?"Redigera planerat köp":"Nytt planerat köp").setView(b).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{String name=n.getText().toString().trim();double amount=num(am);if(name.isEmpty()||amount<=0)return;JSONObject o=j("name",name,"amount",amount,"category",cat.getSelectedItem().toString(),"account",acc.getSelectedItem().toString());JSONArray src=arr("planned"),out=new JSONArray();if(ix>=0){for(int i=0;i<src.length();i++)out.put(i==ix?o:src.optJSONObject(i));}else{for(int i=0;i<src.length();i++)out.put(src.optJSONObject(i));out.put(o);}save("planned",out);showPlannedPurchases();}).show();}
  void deletePlannedV191(int ix){JSONArray a=arr("planned");JSONObject o=a.optJSONObject(ix);if(o==null)return;new AlertDialog.Builder(this).setTitle("Ta bort planerat köp?").setMessage(o.optString("name")+" tas bort från listan.").setNegativeButton("Avbryt",null).setPositiveButton("Ta bort",(d,w)->{JSONArray out=new JSONArray();for(int i=0;i<a.length();i++)if(i!=ix)out.put(a.optJSONObject(i));save("planned",out);showPlannedPurchases();}).show();}
  void completePlannedV191(int ix){JSONArray a=arr("planned");JSONObject o=a.optJSONObject(ix);if(o==null)return;new AlertDialog.Builder(this).setTitle("Genomför köp?").setMessage(o.optString("name")+" läggs till som en riktig utgift på "+fmt(o.optDouble("amount"))+".").setNegativeButton("Avbryt",null).setPositiveButton("Genomför",(d,w)->{String[] ac=accountNames();String account=o.optString("account",ac.length>0?ac[0]:"Lönekonto");String category=o.optString("category","Övrigt");JSONArray tx=arr("tx");tx.put(j("name",o.optString("name"),"amount",o.optDouble("amount"),"type","Utgift","category",category,"account",account,"date",today(),"fromPlanned",true));save("tx",tx);rememberRule(o.optString("name"),category);JSONArray out=new JSONArray();for(int i=0;i<a.length();i++)if(i!=ix)out.put(a.optJSONObject(i));save("planned",out);Toast.makeText(this,"Köpet är genomfört och bokfört som utgift",Toast.LENGTH_LONG).show();showPlannedPurchases();}).show();}
'''
lines[insert:insert]=extra.splitlines()
p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
