from pathlib import Path
p=Path('app/src/main/java/se/minekonomi/app/MainActivity.java')
s=p.read_text(encoding='utf-8')
s=s.replace('Min Ekonomi v2.2.9','Min Ekonomi v2.2.10')
start=s.find('  void addInsightsV18(){')
if start<0: raise SystemExit('addInsightsV18 missing')
end=s.find('\n  void ',start+5)
if end<0: raise SystemExit('end missing')
new=r'''  void addInsightsV18(){section("Smarta insikter");String mk=monthKey(Calendar.getInstance());Calendar now=Calendar.getInstance(),prev=(Calendar)now.clone();prev.add(Calendar.MONTH,-1);int day=now.get(Calendar.DAY_OF_MONTH);double curSame=spendUntilDay(mk,day),oldSame=spendUntilDay(monthKey(prev),day),cur=totals(mk)[1],free=spendableNowV226();int daysLeft=daysToNextSalaryV21();double perDay=daysLeft>0?Math.max(0,free)/daysLeft:Math.max(0,free);LinearLayout c=card();TextView main=tv("Du har "+fmt(free)+" kvar till nästa lön • cirka "+fmt(perDay)+" per dag.",14,true);main.setTextColor(free>=0?ACCENT:RED);c.addView(main);double planned=goalPlannedMonthlyV224(),saved=0;JSONArray gs=arr("goals");for(int i=0;i<gs.length();i++){JSONObject g=gs.optJSONObject(i);if(g!=null)saved+=goalSavedThisMonthV225(g.optString("name"));}if(planned>0){double left=Math.max(0,planned-saved);String st=saved>=planned?"✓ Månadens planerade sparande är uppnått: "+fmt(saved):"Du har sparat "+fmt(saved)+" av planerade "+fmt(planned)+" • "+fmt(left)+" kvar.";TextView sv=tv(st,13,true);sv.setTextColor(saved>=planned?ACCENT:AMBER);sv.setPadding(0,dp(8),0,0);c.addView(sv);}if(oldSame>0){double diff=curSame-oldSame;TextView x=tv((diff<=0?"↓ ":"↑ ")+"Du har spenderat "+fmt(Math.abs(diff))+(diff<=0?" mindre":" mer")+" än vid samma tid förra månaden.",13,true);x.setTextColor(diff<=0?ACCENT:RED);x.setPadding(0,dp(8),0,0);c.addView(x);}else{TextView x=tv("Fortsätt registrera poster – jämförelsen blir smartare med mer historik.",13,false);x.setTextColor(MUTED);x.setPadding(0,dp(8),0,0);c.addView(x);}ArrayList<JSONObject> rows=new ArrayList<>();for(String cat:BUDGET_CATS){double v=categorySpend(cat,mk);if(v>0)rows.add(j("cat",cat,"v",v));}Collections.sort(rows,(a,b)->Double.compare(b.optDouble("v"),a.optDouble("v")));if(rows.size()>0){JSONObject top=rows.get(0);TextView x=tv("Största utgiftskategori: "+top.optString("cat")+" ("+fmt(top.optDouble("v"))+")",13,false);x.setTextColor(MUTED);x.setPadding(0,dp(8),0,0);c.addView(x);}TextView pr=tv("Registrerade utgifter denna månad: "+fmt(cur),13,false);pr.setTextColor(MUTED);pr.setPadding(0,dp(6),0,0);c.addView(pr);content.addView(c);}'''
s=s[:start]+new+s[end:]
p.write_text(s,encoding='utf-8')
