from pathlib import Path
p=Path('app/src/main/java/se/minekonomi/app/MainActivity.java')
s=p.read_text(encoding='utf-8')
start=s.find('  void showSettings(){')
end=s.find('\n  void authenticateThenOpen()',start)
if start<0 or end<0: raise SystemExit('showSettings anchor missing')
new=r'''  void showSettings(){shell("Inställningar",2);TextView backupsV22=action("💾 Automatiska säkerhetskopior");backupsV22.setOnClickListener(v->showSafetyCopiesV22());content.addView(backupsV22);TextView calV21=action("📅 Ekonomikalender");calV21.setOnClickListener(v->showEconomyCalendarV21());content.addView(calV21);section("Ekonomi");TextView pay=small("Lönedag "+salaryDay()+":e • planerat sparande "+fmt(plannedSavings()),Color.rgb(50,77,101));pay.setOnClickListener(v->paySettingsDialog());content.addView(pay);section("Säkerhet");TextView bio=small((p.getBoolean("biometricLock",false)?"✓ ":"")+"Biometriskt applås",Color.rgb(50,77,101));bio.setOnClickListener(v->{boolean nv=!p.getBoolean("biometricLock",false);p.edit().putBoolean("biometricLock",nv).apply();Toast.makeText(this,nv?"Biometriskt applås aktiverat.":"Biometriskt applås avstängt.",Toast.LENGTH_LONG).show();showSettings();});content.addView(bio);section("Notiser");TextView no=small((p.getBoolean("notifications",true)?"✓ ":"")+"Räknings- och budgetnotiser",Color.rgb(50,77,101));no.setOnClickListener(v->{p.edit().putBoolean("notifications",!p.getBoolean("notifications",true)).apply();showSettings();});content.addView(no);TextView test=small("🔔 Testa notis",Color.rgb(50,77,101));test.setOnClickListener(v->{notifyNow(2099,"Min Ekonomi","Testnotis – notiser fungerar ✅");Toast.makeText(this,"Testnotis skickad.",Toast.LENGTH_SHORT).show();});content.addView(test);section("Backup & data");TextView info=tv("Spara backup till valfri plats via Android – till exempel Google Drive, OneDrive, USB eller telefonen.",13,false);info.setTextColor(MUTED);info.setPadding(dp(2),0,dp(2),dp(10));content.addView(info);LinearLayout bk=new LinearLayout(this);TextView ex=small("☁ Spara backup…",Color.rgb(50,77,101)),im=small("↻ Återställ backup…",Color.rgb(50,77,101));ex.setOnClickListener(v->startExport());im.setOnClickListener(v->startImport());bk.addView(ex,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(8),0,0,0);bk.addView(im,lp);content.addView(bk);String last=p.getString("lastManualBackupV301","");TextView ls=tv(last.isEmpty()?"Ingen manuell backup sparad ännu.":"Senaste backup: "+last,12,false);ls.setTextColor(MUTED);ls.setPadding(dp(2),dp(8),0,dp(8));content.addView(ls);if(p.contains("preRestoreBackupV301")){TextView undo=small("Återställ data från före senaste import",Color.rgb(50,77,101));undo.setOnClickListener(v->restorePreImportV301());content.addView(undo);}TextView csv=small("Importera bank-CSV",Color.rgb(50,77,101));csv.setOnClickListener(v->startCsvImport());content.addView(csv);TextView csvout=small("Exportera transaktioner CSV",Color.rgb(50,77,101));csvout.setOnClickListener(v->exportCsvV19());content.addView(csvout);section("Om appen");TextView ver=tv("Min Ekonomi v"+appVersionV301()+"\nDin ekonomi. Enkelt och privat.",14,false);ver.setTextColor(MUTED);content.addView(ver);}'''
s=s[:start]+new+s[end:]
p.write_text(s,encoding='utf-8')
