package se.smartgallery.app;

import android.app.*;import android.graphics.*;import android.graphics.PointF;import android.widget.*;import com.google.android.gms.tasks.Tasks;import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.face.*;import org.tensorflow.lite.Interpreter;import java.io.*;import java.util.*;import java.util.concurrent.TimeUnit;

public class MainActivity20 extends MainActivity19{
 @Override void smartHub(){String[]a={"👥 Personer 6.0","⧉ Riktiga dubbletter (SHA-256)","◫ Liknande bilder","★ Favoriter","📱 S23 Ultra","🗑 Papperskorg","ℹ Bildinformation"};new AlertDialog.Builder(this).setTitle("✨ Smart Gallery 2.0.2").setItems(a,(d,w)->{if(w==0)peoplePage();else if(w==1)findTrueDuplicates17();else if(w==2)findSimilar();else if(w==3){filter="Favoriter";showMain();applyFilter();}else if(w==4)s23Page17();else if(w==5)trashSelected17();else imageInfoHelp();}).setNegativeButton("Stäng",null).show();}
 @Override void peoplePage(){String[]a={"👤 Hitta samma person – Alignment 6.0","🧠 Bygg om personindex 6.0","🧪 Diagnostik","🏷 Namnge person","🔒 Om analysen"};new AlertDialog.Builder(this).setTitle("👥 Personer 6.0").setItems(a,(d,w)->{if(w==0)search20();else if(w==1)index20(null,true);else if(w==2)diagnose20();else if(w==3)namePerson();else new AlertDialog.Builder(this).setTitle("Lokal analys").setMessage("2.0.2 rätar upp varje ansikte med ögonens position före MobileFaceNet. ML Kit hittar ansikte och landmarks. Ansiktet roteras och placeras i en standardiserad 112×112-yta före embedding. Det gamla personindexet används inte och all analys sker lokalt.").setPositiveButton("OK",null).show();}).setNegativeButton("Stäng",null).show();}
 void search20(){ArrayList<Item>r=selectedItems();r.removeIf(Item::video);if(r.isEmpty()){Toast.makeText(this,"Markera 1–5 säkra bilder av personen",Toast.LENGTH_LONG).show();return;}if(r.size()>5)r=new ArrayList<>(r.subList(0,5));index20(r,false);}
 void index20(ArrayList<Item>refs,boolean rebuild){ProgressDialog pd=new ProgressDialog(this);pd.setTitle("🧠 Personer 6.0");pd.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);pd.setMax(all.size());pd.setCancelable(true);pd.show();final ArrayList<Item>rr=refs;pool.execute(()->{Interpreter tf=null;FaceDetector det=null;try{tf=new Interpreter(loadModel18());FaceDetectorOptions o=new FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL).setMinFaceSize(.03f).build();det=FaceDetection.getClient(o);File cache=new File(getFilesDir(),"face-embeddings-v6-aligned.txt");HashMap<String,ArrayList<float[]>>idx=rebuild?new HashMap<>():readEmb18(cache);int n=0,faces=0;for(Item i:all){if(pd.isCancelled())break;n++;if(!i.video()&&!idx.containsKey(i.uri.toString())){try{ArrayList<float[]>e=embeddings20(faceBitmap(i),det,tf);idx.put(i.uri.toString(),e);faces+=e.size();}catch(Exception ignored){}}if(n%8==0){final int N=n,F=faces;runOnUiThread(()->{pd.setProgress(N);pd.setMessage("Bild "+N+" / "+all.size()+" • ansikten "+F);});}}writeEmb18(cache,idx);if(rr==null){runOnUiThread(()->{pd.dismiss();new AlertDialog.Builder(this).setTitle("Personindex 6.0 klart").setMessage(idx.size()+" bilder indexerade.\n\nNu används landmark-justerade ansikten.").setPositiveButton("OK",null).show();});return;}ArrayList<float[]>seeds=new ArrayList<>();for(Item r:rr){ArrayList<float[]>e=embeddings20(faceBitmap(r),det,tf);if(!e.isEmpty())seeds.add(e.get(0));}if(seeds.isEmpty())throw new Exception("Inget tydligt ansikte hittades i referenserna");HashMap<String,Float>scores=new HashMap<>();for(Map.Entry<String,ArrayList<float[]>>en:idx.entrySet()){float best=-1;for(float[]x:en.getValue())for(float[]s:seeds)best=Math.max(best,cos18(x,s));scores.put(en.getKey(),best);}ArrayList<Map.Entry<String,Float>>rank=new ArrayList<>(scores.entrySet());rank.sort((a,b)->Float.compare(b.getValue(),a.getValue()));HashSet<String>keep=new HashSet<>();for(int i=0;i<Math.min(250,rank.size());i++)if(rank.get(i).getValue()>=.12f)keep.add(rank.get(i).getKey());ArrayList<Item>cand=new ArrayList<>();HashSet<String>seen=new HashSet<>();for(Item i:all)if(keep.contains(i.uri.toString())&&seen.add(i.uri.toString()))cand.add(i);cand.sort((a,b)->Float.compare(scores.get(b.uri.toString()),scores.get(a.uri.toString())));int A=0,B=0,C=0;for(Item i:cand){float s=scores.get(i.uri.toString());if(s>=.55f)A++;else if(s>=.35f)B++;else C++;}final int FA=A,FB=B,FC=C;runOnUiThread(()->{pd.dismiss();showAdaptiveResults(cand,FA,FB,FC);});}catch(Exception e){final String m=e.getMessage();runOnUiThread(()->{pd.dismiss();new AlertDialog.Builder(this).setTitle("Personer 6.0").setMessage("Analysen kunde inte slutföras\n\n"+m).setPositiveButton("OK",null).show();});}finally{if(det!=null)det.close();if(tf!=null)tf.close();}});}
 void diagnose20(){new AlertDialog.Builder(this).setTitle("🧪 Diagnostik 6.0").setMessage("Version 2.0.2 använder ett nytt separat index. Kör först ‘Bygg om personindex 6.0’. Sökningen visar upp till 250 närmaste kandidater så att en för hård tröskel inte längre kan ge bara referensbilden.").setPositiveButton("OK",null).show();}
 ArrayList<float[]> embeddings20(Bitmap b,FaceDetector d,Interpreter tf)throws Exception{ArrayList<float[]>out=new ArrayList<>();if(b==null)return out;List<Face>fs=Tasks.await(d.process(InputImage.fromBitmap(b,0)),30,TimeUnit.SECONDS);int[]sh=tf.getInputTensor(0).shape();int h=sh[1],w=sh[2],od=1;for(int x:tf.getOutputTensor(0).shape())od*=x;for(Face f:fs){Bitmap c=aligned20(b,f,w,h);if(c==null)continue;java.nio.ByteBuffer input=java.nio.ByteBuffer.allocateDirect(4*w*h*3).order(java.nio.ByteOrder.nativeOrder());for(int y=0;y<h;y++)for(int x=0;x<w;x++){int z=c.getPixel(x,y);input.putFloat((Color.red(z)-127.5f)/128f);input.putFloat((Color.green(z)-127.5f)/128f);input.putFloat((Color.blue(z)-127.5f)/128f);}input.rewind();float[][]o=new float[1][od];tf.run(input,o);norm18(o[0]);out.add(o[0]);}return out;}
 Bitmap aligned20(Bitmap b,Face f,int w,int h){try{FaceLandmark le=f.getLandmark(FaceLandmark.LEFT_EYE),re=f.getLandmark(FaceLandmark.RIGHT_EYE);Rect q=f.getBoundingBox();if(le==null||re==null)return fallback20(b,q,w,h);PointF L=le.getPosition(),R=re.getPosition();float dx=R.x-L.x,dy=R.y-L.y,dist=(float)Math.sqrt(dx*dx+dy*dy);if(dist<8)return fallback20(b,q,w,h);float angle=(float)Math.toDegrees(Math.atan2(dy,dx));float targetDist=w*.315f,scale=targetDist/dist;float midx=(L.x+R.x)/2f,midy=(L.y+R.y)/2f;Matrix m=new Matrix();m.postTranslate(-midx,-midy);m.postRotate(-angle);m.postScale(scale,scale);m.postTranslate(w*.5f,h*.46f);Bitmap out=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);c.drawColor(Color.BLACK);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);c.drawBitmap(b,m,p);return out;}catch(Exception e){return fallback20(b,f.getBoundingBox(),w,h);}}
 Bitmap fallback20(Bitmap b,Rect q,int w,int h){int side=(int)(Math.max(q.width(),q.height())*1.45f),cx=q.centerX(),cy=q.centerY();int l=Math.max(0,cx-side/2),t=Math.max(0,cy-(int)(side*.43f)),r=Math.min(b.getWidth(),l+side),bt=Math.min(b.getHeight(),t+side);if(r-l<20||bt-t<20)return null;return Bitmap.createScaledBitmap(Bitmap.createBitmap(b,l,t,r-l,bt-t),w,h,true);}
}
