package se.smartgallery.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.security.*;import java.util.*;

public class MainActivity14 extends MainActivity13{
 @Override void showMain(){super.showMain();addSmartButton();}
 @Override void openAlbum(Album a){super.openAlbum(a);addSmartButton();}
 void addSmartButton(){if(root==null||root.getChildCount()==0)return;View h=root.getChildAt(0);if(!(h instanceof LinearLayout))return;Button b=button("✨ Smart");b.setOnClickListener(v->smartHub());((LinearLayout)h).addView(b,new LinearLayout.LayoutParams(-2,-2));}
 void smartHub(){String[]a={"👤 Personer","⧉ Exakta dubbletter","◫ Liknande bilder","★ Favoriter","ℹ Bildinformation"};new AlertDialog.Builder(this).setTitle("✨ Smart Gallery").setItems(a,(d,w)->{if(w==0)peoplePage();else if(w==1)findExactDuplicates();else if(w==2)findSimilar();else if(w==3){filter="Favoriter";showMain();applyFilter();}else imageInfoHelp();}).setNegativeButton("Stäng",null).show();}
 void peoplePage(){String[]a={"👤 Hitta person från markerad bild","🏷 Namnge senaste person","🔒 Om personanalys"};new AlertDialog.Builder(this).setTitle("👤 Personer").setMessage("Personanalysen sker lokalt på telefonen. Markera först en tydlig bild av personen i galleriet.").setItems(a,(d,w)->{if(w==0)findSamePerson();else if(w==1)namePerson();else new AlertDialog.Builder(this).setTitle("Lokal analys").setMessage("Bilder skickas inte till någon molntjänst av Smart Gallery. Träffar är förslag och ska granskas innan de flyttas.").setPositiveButton("OK",null).show();}).setPositiveButton("Stäng",null).show();}
 void namePerson(){EditText e=new EditText(this);e.setHint("Personens namn");new AlertDialog.Builder(this).setTitle("🏷 Namnge person").setView(e).setPositiveButton("Spara",(d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty()){Set<String>s=new LinkedHashSet<>(prefs.getStringSet("people_names",Collections.emptySet()));s.add(n);prefs.edit().putStringSet("people_names",s).apply();Toast.makeText(this,"Personen ”"+n+"” sparad",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Avbryt",null).show();}
 void findExactDuplicates(){ProgressDialog pd=ProgressDialog.show(this,"⧉ Dubbletter","Jämför bilder…",true,false);pool.execute(()->{HashMap<String,ArrayList<Item>>m=new HashMap<>();for(Item i:all){if(i.video())continue;String k=i.size+"|"+(i.name==null?"":i.name.replaceFirst("(?i)([-_ ]copy|\\([0-9]+\\))(?=\\.[^.]+$)",""));m.computeIfAbsent(k,x->new ArrayList<>()).add(i);}ArrayList<Item>r=new ArrayList<>();for(ArrayList<Item>g:m.values())if(g.size()>1)r.addAll(g);runOnUiThread(()->{pd.dismiss();showSmartResults("Exakta/möjliga dubbletter",r,"Kontrollera alltid bilderna innan du raderar något.");});});}
 void findSimilar(){ProgressDialog pd=ProgressDialog.show(this,"◫ Liknande bilder","Grupperar bildserier…",true,false);pool.execute(()->{ArrayList<Item>r=new ArrayList<>();ArrayList<Item>imgs=new ArrayList<>();for(Item i:all)if(!i.video())imgs.add(i);Collections.sort(imgs,(x,y)->Long.compare(x.date,y.date));for(int n=1;n<imgs.size();n++){Item a=imgs.get(n-1),b=imgs.get(n);if(Math.abs(b.date-a.date)<=8&&ratio(a.size,b.size)>.55){if(!r.contains(a))r.add(a);r.add(b);}}runOnUiThread(()->{pd.dismiss();showSmartResults("Liknande bildserier",r,"Bilder tagna nära varandra i tid och med liknande filstorlek. Detta är kandidater, inte garanterade kopior.");});});}
 double ratio(long a,long b){if(a<=0||b<=0)return 0;return Math.min(a,b)/(double)Math.max(a,b);}
 void showSmartResults(String title,ArrayList<Item>r,String note){if(r.isEmpty()){new AlertDialog.Builder(this).setTitle(title).setMessage("Inga träffar hittades.").setPositiveButton("OK",null).show();return;}shown.clear();shown.addAll(r);selected.clear();selectionMode=false;baseRoot();LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹");back.setTextSize(28);back.setOnClickListener(v->showMain());h.addView(back,new LinearLayout.LayoutParams(dp(54),-2));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(tv(title,24,true));TextView s=tv(r.size()+" objekt • "+note,12,false);s.setTextColor(ACC);t.addView(s);h.addView(t,new LinearLayout.LayoutParams(0,-2,1));root.addView(h);grid=new GridView(this);grid.setNumColumns(3);grid.setHorizontalSpacing(dp(3));grid.setVerticalSpacing(dp(3));adapter=new SelectAdapter();grid.setAdapter(adapter);grid.setOnItemClickListener((p,v,pos,id)->open(shown.get(pos)));grid.setOnItemLongClickListener((p,v,pos,id)->{selectionMode=true;toggle(shown.get(pos));return true;});root.addView(grid,new LinearLayout.LayoutParams(-1,0,1));selectionBar=new LinearLayout(this);selectionBar.setGravity(Gravity.CENTER);Button mv=button("📁 Flytta");mv.setOnClickListener(v->chooseMoveTarget());selectionBar.addView(mv,new LinearLayout.LayoutParams(0,-2,1));Button sh=button("↗ Dela");sh.setOnClickListener(v->shareSelected());selectionBar.addView(sh,new LinearLayout.LayoutParams(0,-2,1));root.addView(selectionBar);setContentView(root);}
 void imageInfoHelp(){ArrayList<Item>s=selectedItems();if(s.size()!=1){new AlertDialog.Builder(this).setTitle("ℹ Bildinformation").setMessage("Långtryck på exakt en bild först. Smart Gallery kan sedan visa filnamn, mapp, storlek, datum och mediatyp.").setPositiveButton("OK",null).show();return;}Item i=s.get(0);String date=new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.getDefault()).format(new Date(i.date*1000));new AlertDialog.Builder(this).setTitle(i.name).setMessage("Typ: "+i.mime+"\nStorlek: "+human(i.size)+"\nDatum: "+date+"\nMapp: "+i.path+"\n\nURI: "+i.uri).setPositiveButton("OK",null).show();}
}
