package se.smartgallery.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.util.Size;import android.view.*;import android.widget.*;import com.google.android.gms.tasks.Tasks;import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.face.*;import java.io.*;import java.util.*;import java.util.concurrent.TimeUnit;

public class MainActivity15 extends MainActivity14{
 static class Sig{float[] v;Sig(float[]x){v=x;}}
 @Override void peoplePage(){String[]a={"👤 Hitta samma person","🧠 Bygg/uppdatera personindex","🏷 Namnge person","🔒 Om personanalys"};new AlertDialog.Builder(this).setTitle("👥 Personer 2.0").setMessage("Smart Gallery kan nu indexera ansikten en gång och återanvända resultatet. Markera en tydlig bild och välj Hitta samma person.").setItems(a,(d,w)->{if(w==0)findSamePerson15();else if(w==1)buildIndex(null);else if(w==2)namePerson();else new AlertDialog.Builder(this).setTitle("Lokal analys").setMessage("Ansiktsanalysen sker på din telefon. Indexet innehåller matematiska bildsignaturer och URI:er och används bara av Smart Gallery.").setPositiveButton("OK",null).show();}).setPositiveButton("Stäng",null).show();}
 void findSamePerson15(){ArrayList<Item>s=selectedItems();if(s.size()!=1){Toast.makeText(this,"Långtryck och markera exakt en bild",Toast.LENGTH_LONG).show();return;}Item ref=s.get(0);if(ref.video()){Toast.makeText(this,"Välj en bild",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("👤 Hitta samma person").setMessage("Första sökningen bygger ett lokalt index av ditt galleri och kan därför ta en stund. Senare sökningar återanvänder indexet och blir mycket snabbare. Träffarna visas för granskning.").setPositiveButton("Starta",(d,w)->buildIndex(ref)).setNegativeButton("Avbryt",null).show();}
 void buildIndex(Item ref){ProgressDialog pd=new ProgressDialog(this);pd.setTitle("🧠 Personindex");pd.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);pd.setMax(all.size());pd.setMessage("Förbereder lokal analys…");pd.setCancelable(true);pd.show();pool.execute(()->{FaceDetectorOptions opt=new FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL).setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_ALL).setMinFaceSize(.08f).build();FaceDetector det=FaceDetection.getClient(opt);File f=new File(getFilesDir(),"people-index-v2.txt");HashMap<String,ArrayList<Sig>>idx=readIndex(f);int n=0,faces=0;for(Item i:all){if(pd.isCancelled())break;n++;if(!i.video()&&!idx.containsKey(i.uri.toString())){try{ArrayList<Sig>x=signatures(faceBitmap(i),det);idx.put(i.uri.toString(),x);faces+=x.size();}catch(Exception e){idx.put(i.uri.toString(),new ArrayList<>());}}if(n%10==0){final int z=n,fc=faces;runOnUiThread(()->{pd.setProgress(z);pd.setMessage("Analyserat "+z+" av "+all.size()+" • "+fc+" nya ansikten");});}}writeIndex(f,idx);det.close();if(ref==null){runOnUiThread(()->{pd.dismiss();Toast.makeText(this,"Personindex klart • "+idx.size()+" bilder indexerade",Toast.LENGTH_LONG).show();});return;}try{FaceDetector rd=FaceDetection.getClient(opt);ArrayList<Sig>rs=signatures(faceBitmap(ref),rd);rd.close();if(rs.isEmpty()){runOnUiThread(()->{pd.dismiss();Toast.makeText(this,"Kunde inte hitta ett tydligt ansikte i den markerade bilden",Toast.LENGTH_LONG).show();});return;}Sig seed=rs.get(0);ArrayList<Item>matches=new ArrayList<>();for(Item i:all){ArrayList<Sig>xs=idx.get(i.uri.toString());if(xs==null)continue;float best=-9;for(Sig x:xs)best=Math.max(best,similarity(seed,x));if(best>=.54f)matches.add(i);}runOnUiThread(()->{pd.dismiss();showPersonResults(matches);});}catch(Exception e){runOnUiThread(()->{pd.dismiss();Toast.makeText(this,"Personanalysen kunde inte slutföras",Toast.LENGTH_LONG).show();});}});}
 Bitmap faceBitmap(Item i)throws Exception{Bitmap b;if(Build.VERSION.SDK_INT>=29)b=getContentResolver().loadThumbnail(i.uri,new Size(720,720),null);else{InputStream in=getContentResolver().openInputStream(i.uri);b=BitmapFactory.decodeStream(in);if(in!=null)in.close();}return b;}
 ArrayList<Sig> signatures(Bitmap b,FaceDetector d)throws Exception{ArrayList<Sig>r=new ArrayList<>();if(b==null)return r;List<Face>fs=Tasks.await(d.process(InputImage.fromBitmap(b,0)),30,TimeUnit.SECONDS);for(Face face:fs){Rect q=new Rect(face.getBoundingBox());int p=(int)(Math.max(q.width(),q.height())*.22f);q.left=Math.max(0,q.left-p);q.top=Math.max(0,q.top-p);q.right=Math.min(b.getWidth(),q.right+p);q.bottom=Math.min(b.getHeight(),q.bottom+p);if(q.width()<24||q.height()<24)continue;Bitmap c=Bitmap.createBitmap(b,q.left,q.top,q.width(),q.height());Bitmap s=Bitmap.createScaledBitmap(c,24,24,true);float[]v=new float[24*24*3];int k=0;float mean=0;for(int y=0;y<24;y++)for(int x=0;x<24;x++){int z=s.getPixel(x,y);float rr=Color.red(z)/255f,gg=Color.green(z)/255f,bb=Color.blue(z)/255f;v[k++]=rr;v[k++]=gg;v[k++]=bb;mean+=(rr+gg+bb)/3f;}mean/=576f;float norm=0;for(int j=0;j<v.length;j++){v[j]-=mean;norm+=v[j]*v[j];}norm=(float)Math.sqrt(norm)+1e-6f;for(int j=0;j<v.length;j++)v[j]/=norm;r.add(new Sig(v));}return r;}
 float similarity(Sig a,Sig b){if(a==null||b==null||a.v.length!=b.v.length)return-9;float s=0;for(int i=0;i<a.v.length;i++)s+=a.v[i]*b.v[i];return s;}
 HashMap<String,ArrayList<Sig>> readIndex(File f){HashMap<String,ArrayList<Sig>>m=new HashMap<>();if(!f.exists())return m;try{BufferedReader r=new BufferedReader(new FileReader(f));String line;while((line=r.readLine())!=null){String[]p=line.split("\\|",3);if(p.length<2)continue;String u=p[0];ArrayList<Sig>ls=new ArrayList<>();if(p.length==3&&!p[2].isEmpty()){for(String one:p[2].split(";")){String[]z=one.split(",");float[]v=new float[z.length];for(int i=0;i<z.length;i++)v[i]=Float.parseFloat(z[i]);ls.add(new Sig(v));}}m.put(u,ls);}r.close();}catch(Exception e){m.clear();}return m;}
 void writeIndex(File f,HashMap<String,ArrayList<Sig>>m){try{BufferedWriter w=new BufferedWriter(new FileWriter(f));for(Map.Entry<String,ArrayList<Sig>>e:m.entrySet()){w.write(e.getKey()+"|"+e.getValue().size()+"|");boolean firstFace=true;for(Sig s:e.getValue()){if(!firstFace)w.write(";");firstFace=false;for(int i=0;i<s.v.length;i++){if(i>0)w.write(",");w.write(String.format(Locale.ROOT,"%.5f",s.v[i]));}}w.newLine();}w.close();}catch(Exception ignored){}}
}
