package se.smartgallery.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity22 extends MainActivity21{
 @Override void smartHub(){String[]a={"👥 Personer 7.0","🖼 Bildvisare 2.0","✨ Liknande bilder 2.0","⧉ Riktiga dubbletter (SHA-256)","★ Favoriter","📱 S23 Ultra","🗑 Papperskorg","ℹ Bildinformation"};new AlertDialog.Builder(this).setTitle("✨ Smart Gallery 2.2").setItems(a,(d,w)->{if(w==0)peoplePage();else if(w==1)Toast.makeText(this,"Tryck på en bild för Smart Gallery-visaren",Toast.LENGTH_LONG).show();else if(w==2)findSimilar22();else if(w==3)findTrueDuplicates17();else if(w==4){filter="Favoriter";showMain();applyFilter();}else if(w==5)s23Page17();else if(w==6)trashSelected17();else imageInfoHelp();}).setNegativeButton("Stäng",null).show();}
 @Override void open(Item item){viewer22(item);}
 void viewer22(Item item){if(item.video()){super.open(item);return;}final int[] pos={Math.max(0,shown.indexOf(item))};LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(Color.rgb(5,8,12));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹");back.setTextSize(30);back.setOnClickListener(v->showMain());top.addView(back,new LinearLayout.LayoutParams(dp(56),dp(56)));TextView title=tv("Bild",20,true);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));page.addView(top);ImageView iv=new ImageView(this);iv.setScaleType(ImageView.ScaleType.FIT_CENTER);page.addView(iv,new LinearLayout.LayoutParams(-1,0,1));TextView inf=tv("",12,false);inf.setGravity(Gravity.CENTER);page.addView(inf);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER);Button prev=button("‹"),fav=button("☆"),share=button("Dela"),next=button("›");bar.addView(prev,new LinearLayout.LayoutParams(0,-2,1));bar.addView(fav,new LinearLayout.LayoutParams(0,-2,1));bar.addView(share,new LinearLayout.LayoutParams(0,-2,1));bar.addView(next,new LinearLayout.LayoutParams(0,-2,1));page.addView(bar);final Runnable[] load={null};load[0]=()->{if(shown.isEmpty())return;pos[0]=Math.max(0,Math.min(pos[0],shown.size()-1));Item x=shown.get(pos[0]);if(x.video())return;try{iv.setImageBitmap(faceBitmap(x));}catch(Exception e){iv.setImageURI(x.uri);}title.setText(x.name);inf.setText((pos[0]+1)+" / "+shown.size()+"   •   "+human(x.size));fav.setText(prefs.getBoolean("fav_"+x.uri,false)?"★":"☆");};prev.setOnClickListener(v->{if(pos[0]>0){pos[0]--;load[0].run();}});next.setOnClickListener(v->{if(pos[0]<shown.size()-1){pos[0]++;load[0].run();}});fav.setOnClickListener(v->{Item x=shown.get(pos[0]);String k="fav_"+x.uri;boolean now=!prefs.getBoolean(k,false);prefs.edit().putBoolean(k,now).apply();load[0].run();});share.setOnClickListener(v->{Item x=shown.get(pos[0]);Intent s=new Intent(Intent.ACTION_SEND);s.setType(x.mime);s.putExtra(Intent.EXTRA_STREAM,x.uri);s.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(s,"Dela bild"));});iv.setOnTouchListener(new View.OnTouchListener(){float down;public boolean onTouch(View v,MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){down=e.getX();return true;}if(e.getAction()==MotionEvent.ACTION_UP){float dx=e.getX()-down;if(Math.abs(dx)>120){if(dx<0&&pos[0]<shown.size()-1)pos[0]++;else if(dx>0&&pos[0]>0)pos[0]--;load[0].run();}return true;}return true;}});setContentView(page);load[0].run();}
 void findSimilar22(){ProgressDialog pd=new ProgressDialog(this);pd.setTitle("✨ Liknande bilder 2.0");pd.setMessage("Jämför bildinnehåll…");pd.setCancelable(false);pd.show();pool.execute(()->{ArrayList<Item> imgs=new ArrayList<>();for(Item i:all)if(!i.video())imgs.add(i);imgs.sort((a,b)->Long.compare(b.date,a.date));ArrayList<Item> out=new ArrayList<>();HashSet<String> seen=new HashSet<>();long prevHash=-1;Item prev=null;for(Item i:imgs){try{long h=dhash22(i);if(prev!=null&&Math.abs(i.date-prev.date)<=120000&&ham22(h,prevHash)<=12){if(seen.add(prev.uri.toString()))out.add(prev);if(seen.add(i.uri.toString()))out.add(i);}prev=i;prevHash=h;}catch(Exception ignored){}}runOnUiThread(()->{pd.dismiss();if(out.isEmpty())new AlertDialog.Builder(this).setTitle("Liknande bilder 2.0").setMessage("Inga tydliga liknande bildpar hittades.").setPositiveButton("OK",null).show();else showAdaptiveResults(out,0,out.size(),0);});});}
 long dhash22(Item i)throws Exception{Bitmap b=faceBitmap(i);Bitmap s=Bitmap.createScaledBitmap(b,9,8,true);long h=0;int bit=0;for(int y=0;y<8;y++)for(int x=0;x<8;x++){int a=s.getPixel(x,y),c=s.getPixel(x+1,y);int ga=(Color.red(a)*30+Color.green(a)*59+Color.blue(a)*11)/100;int gc=(Color.red(c)*30+Color.green(c)*59+Color.blue(c)*11)/100;if(ga>gc)h|=(1L<<bit);bit++;}return h;}
 int ham22(long a,long b){return Long.bitCount(a^b);}
}
