package se.smartgallery.app;

import android.app.*;import android.content.*;import android.view.*;import android.widget.*;import com.google.mlkit.vision.face.*;import java.io.*;import java.util.*;

public class MainActivity16 extends MainActivity15{
 final ArrayList<Item> personRefs=new ArrayList<>();
 @Override void peoplePage(){String[]a={"👤 Sök med markerade referensbilder","➕ Lägg markerade till personprofil","🧹 Töm personprofil","🧠 Bygg/uppdatera personindex","🏷 Namnge person"};new AlertDialog.Builder(this).setTitle("👥 Personer 3.0").setMessage("Använd gärna 3–5 tydliga bilder av samma person från olika vinklar/år. Smart Gallery jämför då varje ansikte mot hela profilen och delar upp resultaten efter säkerhet.").setItems(a,(d,w)->{if(w==0)searchAdaptive();else if(w==1)addRefs();else if(w==2){personRefs.clear();Toast.makeText(this,"Personprofil tömd",Toast.LENGTH_SHORT).show();}else if(w==3)buildIndex(null);else namePerson();}).setPositiveButton("Stäng",null).show();}
 void addRefs(){ArrayList<Item>s=selectedItems();if(s.isEmpty()){Toast.makeText(this,"Markera en eller flera bilder först",Toast.LENGTH_LONG).show();return;}for(Item i:s)if(!i.video()&&!personRefs.contains(i))personRefs.add(i);Toast.makeText(this,personRefs.size()+" referensbilder i personprofilen",Toast.LENGTH_LONG).show();}
 void searchAdaptive(){ArrayList<Item>s=selectedItems();for(Item i:s)if(!i.video()&&!personRefs.contains(i))personRefs.add(i);if(personRefs.isEmpty()){Toast.makeText(this,"Markera minst en tydlig bild av personen",Toast.LENGTH_LONG).show();return;}new AlertDialog.Builder(this).setTitle("👤 Sök med "+personRefs.size()+" referensbilder").setMessage("Säkra, möjliga och svagare kandidater tas med. Ju fler korrekta referensbilder du använder, desto bättre täckning får sökningen.").setPositiveButton("Sök",(d,w)->runAdaptive()).setNegativeButton("Avbryt",null).show();}
 void runAdaptive(){ProgressDialog pd=new ProgressDialog(this);pd.setTitle("👤 Personer 3.0");pd.setMessage("Läser personindex…");pd.setCancelable(true);pd.show();pool.execute(()->{File f=new File(getFilesDir(),"people-index-v2.txt");HashMap<String,ArrayList<Sig>>idx=readIndex(f);if(idx.size()<Math.max(10,all.size()/3)){runOnUiThread(()->{pd.dismiss();new AlertDialog.Builder(this).setTitle("Index behöver uppdateras").setMessage("Bygg personindex först. När det är klart, kör sökningen igen. Indexet sparas så detta behöver normalt bara göras för nya bilder.").setPositiveButton("Bygg nu",(d,w)->buildIndex(null)).setNegativeButton("Senare",null).show();});return;}ArrayList<Sig>refs=new ArrayList<>();try{FaceDetectorOptions o=new FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL).setMinFaceSize(.08f).build();FaceDetector det=FaceDetection.getClient(o);for(Item r:personRefs){ArrayList<Sig>x=signatures(faceBitmap(r),det);if(!x.isEmpty())refs.add(x.get(0));}det.close();}catch(Exception ignored){}if(refs.isEmpty()){runOnUiThread(()->{pd.dismiss();Toast.makeText(this,"Inget tydligt ansikte hittades i referensbilderna",Toast.LENGTH_LONG).show();});return;}ArrayList<Scored>sc=new ArrayList<>();for(Item i:all){ArrayList<Sig>xs=idx.get(i.uri.toString());if(xs==null||xs.isEmpty())continue;float best=-9;for(Sig x:xs)for(Sig r:refs)best=Math.max(best,similarity(r,x));if(best>=.30f)sc.add(new Scored(i,best));}Collections.sort(sc,(a,b)->Float.compare(b.score,a.score));ArrayList<Item>sure=new ArrayList<>(),possible=new ArrayList<>(),weak=new ArrayList<>();for(Scored q:sc){if(q.score>=.52f)sure.add(q.item);else if(q.score>=.40f)possible.add(q.item);else weak.add(q.item);}ArrayList<Item>out=new ArrayList<>();out.addAll(sure);out.addAll(possible);out.addAll(weak);runOnUiThread(()->{pd.dismiss();showAdaptiveResults(out,sure.size(),possible.size(),weak.size());});});}
 static class Scored{Item item;float score;Scored(Item i,float s){item=i;score=s;}}
 void showAdaptiveResults(ArrayList<Item>r,int sure,int poss,int weak){if(r.isEmpty()){new AlertDialog.Builder(this).setTitle("Personträffar").setMessage("Inga kandidater hittades. Prova att lägga till fler tydliga referensbilder från olika vinklar eller år.").setPositiveButton("OK",null).show();return;}returnScreen=screen;screen=3;selected.clear();selectionMode=true;for(int i=0;i<sure+poss&&i<r.size();i++)selected.add(r.get(i).uri.toString());baseRoot();LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹");back.setTextSize(28);back.setOnClickListener(v->onBackPressed());h.addView(back,new LinearLayout.LayoutParams(dp(54),-2));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(tv("Personträffar",25,true));TextView sub=tv("✓ "+sure+" säkra  •  ? "+poss+" möjliga  •  ◌ "+weak+" svaga",13,false);sub.setTextColor(ACC);t.addView(sub);h.addView(t,new LinearLayout.LayoutParams(0,-2,1));root.addView(h);shown.clear();shown.addAll(r);grid=new GridView(this);grid.setNumColumns(3);grid.setHorizontalSpacing(dp(3));grid.setVerticalSpacing(dp(3));adapter=new SelectAdapter();grid.setAdapter(adapter);grid.setOnItemClickListener((p,v,pos,id)->toggle(shown.get(pos)));grid.setOnItemLongClickListener((p,v,pos,id)->{Item x=shown.get(pos);if(!personRefs.contains(x))personRefs.add(x);Toast.makeText(this,"Tillagd som referens • "+personRefs.size()+" totalt",Toast.LENGTH_SHORT).show();return true;});root.addView(grid,new LinearLayout.LayoutParams(-1,0,1));selectionBar=new LinearLayout(this);Button move=button("📁 Flytta markerade");move.setOnClickListener(v->chooseMoveTarget());selectionBar.addView(move,new LinearLayout.LayoutParams(0,-2,1));Button learn=button("🧠 Lär av markerade");learn.setOnClickListener(v->{ArrayList<Item>x=selectedItems();for(Item i:x)if(!personRefs.contains(i))personRefs.add(i);Toast.makeText(this,"Personprofilen har nu "+personRefs.size()+" referenser",Toast.LENGTH_LONG).show();});selectionBar.addView(learn,new LinearLayout.LayoutParams(0,-2,1));root.addView(selectionBar);setContentView(root);updateSelection();}
}
