package se.smartgallery.app;

import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.security.*;import java.util.*;

public class MainActivity17 extends MainActivity16{
 static final int REQ_TRASH17=1717;
 ArrayList<Item> pendingTrash17=new ArrayList<>();
 @Override void smartHub(){String[]a={"👤 Personer 3.0","⧉ Riktiga dubbletter (SHA-256)","◫ Liknande bilder","★ Favoriter","📱 S23 Ultra","🗑 Papperskorg","ℹ Bildinformation"};new AlertDialog.Builder(this).setTitle("✨ Smart Gallery 1.7").setItems(a,(d,w)->{if(w==0)peoplePage();else if(w==1)findTrueDuplicates17();else if(w==2)findSimilar();else if(w==3){filter="Favoriter";showMain();applyFilter();}else if(w==4)s23Page17();else if(w==5)trashSelected17();else imageInfoHelp();}).setNegativeButton("Stäng",null).show();}
 void findTrueDuplicates17(){ProgressDialog pd=new ProgressDialog(this);pd.setTitle("⧉ Riktiga dubbletter");pd.setMessage("Grupperar filer efter storlek…");pd.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);pd.setMax(all.size());pd.setCancelable(true);pd.show();pool.execute(()->{HashMap<Long,ArrayList<Item>>bySize=new HashMap<>();for(Item i:all)if(!i.video()&&i.size>0)bySize.computeIfAbsent(i.size,x->new ArrayList<>()).add(i);HashMap<String,ArrayList<Item>>groups=new HashMap<>();int n=0;for(ArrayList<Item>g:bySize.values()){if(g.size()<2){n+=g.size();continue;}for(Item i:g){if(pd.isCancelled())break;n++;try{String h=sha256(i.uri);groups.computeIfAbsent(i.size+"|"+h,x->new ArrayList<>()).add(i);}catch(Exception ignored){}if(n%5==0){final int z=n;runOnUiThread(()->{pd.setProgress(z);pd.setMessage("Kontrollerat "+z+" av "+all.size());});}}}ArrayList<Item>r=new ArrayList<>();int sets=0;for(ArrayList<Item>g:groups.values())if(g.size()>1){sets++;r.addAll(g);}final int fs=sets;runOnUiThread(()->{pd.dismiss();showSmartResults("Riktiga dubbletter",r,fs+" identiska grupper • SHA-256 • granska innan radering");});});}
 String sha256(Uri u)throws Exception{MessageDigest md=MessageDigest.getInstance("SHA-256");InputStream in=getContentResolver().openInputStream(u);if(in==null)throw new IOException();byte[]b=new byte[65536];int n;while((n=in.read(b))>0)md.update(b,0,n);in.close();StringBuilder s=new StringBuilder();for(byte x:md.digest())s.append(String.format(Locale.ROOT,"%02x",x));return s.toString();}
 void s23Page17(){String[]a={"📸 200 MP / extremt hög upplösning","📷 50 MP / hög upplösning","🧪 RAW / Expert RAW","▣ Skärmbilder","◉ Stora filer"};new AlertDialog.Builder(this).setTitle("📱 Galaxy S23 Ultra").setMessage("Snabbfilter anpassade för ett stort mobilgalleri. Upplösningsfiltren använder bildmetadata när Android kan läsa den.").setItems(a,(d,w)->{if(w==2)showByName17("RAW / Expert RAW",".dng","raw","expert");else if(w==3){filter="Skärmbilder";showMain();applyFilter();}else if(w==4){filter="Stora filer";showMain();applyFilter();}else scanResolution17(w==0?150_000_000L:40_000_000L,w==0?"200 MP / extremt hög upplösning":"50 MP / hög upplösning");}).setPositiveButton("Stäng",null).show();}
 void showByName17(String title,String...terms){ArrayList<Item>r=new ArrayList<>();for(Item i:all){String x=((i.name==null?"":i.name)+" "+(i.path==null?"":i.path)+" "+(i.mime==null?"":i.mime)).toLowerCase(Locale.ROOT);for(String t:terms)if(x.contains(t.toLowerCase(Locale.ROOT))){r.add(i);break;}}showSmartResults(title,r,"lokalt filter");}
 void scanResolution17(long minPixels,String title){ProgressDialog pd=ProgressDialog.show(this,title,"Läser bilddimensioner…",true,false);pool.execute(()->{ArrayList<Item>r=new ArrayList<>();for(Item i:all){if(i.video())continue;try{android.graphics.BitmapFactory.Options o=new android.graphics.BitmapFactory.Options();o.inJustDecodeBounds=true;InputStream in=getContentResolver().openInputStream(i.uri);android.graphics.BitmapFactory.decodeStream(in,null,o);if(in!=null)in.close();long px=(long)o.outWidth*(long)o.outHeight;if(px>=minPixels)r.add(i);}catch(Exception ignored){}}runOnUiThread(()->{pd.dismiss();showSmartResults(title,r,"baserat på faktisk bildstorlek");});});}
 void trashSelected17(){ArrayList<Item>s=selectedItems();if(s.isEmpty()){new AlertDialog.Builder(this).setTitle("🗑 Papperskorg").setMessage("Långtryck och markera en eller flera bilder först. De skickas till Androids papperskorg när systemet stödjer det.").setPositiveButton("OK",null).show();return;}new AlertDialog.Builder(this).setTitle("Flytta till papperskorgen?").setMessage(s.size()+" markerade objekt. Android visar en systembekräftelse innan något flyttas.").setPositiveButton("Fortsätt",(d,w)->beginTrash17(s)).setNegativeButton("Avbryt",null).show();}
 void beginTrash17(ArrayList<Item>s){pendingTrash17=new ArrayList<>(s);if(Build.VERSION.SDK_INT>=30){try{ArrayList<Uri>u=new ArrayList<>();for(Item i:s)u.add(i.uri);PendingIntent pi=MediaStore.createTrashRequest(getContentResolver(),u,true);startIntentSenderForResult(pi.getIntentSender(),REQ_TRASH17,null,0,0,0);return;}catch(Exception e){Toast.makeText(this,"Papperskorgen kunde inte öppnas",Toast.LENGTH_LONG).show();}}else Toast.makeText(this,"Systempapperskorg kräver Android 11 eller senare",Toast.LENGTH_LONG).show();}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==REQ_TRASH17){if(c==RESULT_OK){Toast.makeText(this,pendingTrash17.size()+" objekt flyttades till papperskorgen",Toast.LENGTH_LONG).show();selected.clear();selectionMode=false;load();}else Toast.makeText(this,"Papperskorgen avbröts",Toast.LENGTH_SHORT).show();}}
}
