package se.smartgallery.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity21 extends MainActivity20{
 static final String PA_PREF="person_albums_7";
 @Override void smartHub(){String[]a={"👥 Personer 7.0","⧉ Riktiga dubbletter (SHA-256)","◫ Liknande bilder","★ Favoriter","📱 S23 Ultra","🗑 Papperskorg","ℹ Bildinformation"};new AlertDialog.Builder(this).setTitle("✨ Smart Gallery 2.1").setItems(a,(d,w)->{if(w==0)peoplePage();else if(w==1)findTrueDuplicates17();else if(w==2)findSimilar();else if(w==3){filter="Favoriter";showMain();applyFilter();}else if(w==4)s23Page17();else if(w==5)trashSelected17();else imageInfoHelp();}).setNegativeButton("Stäng",null).show();}
 @Override void peoplePage(){String[]a={"🖼 Personalbum","➕ Skapa personalbum från markerade","👤 Hitta samma person – Alignment 6.0","🧠 Bygg om personindex 6.0","🧪 Diagnostik","🔒 Om analysen"};new AlertDialog.Builder(this).setTitle("👥 Personer 7.0").setItems(a,(d,w)->{if(w==0)showPersonAlbums21();else if(w==1)createPersonAlbum21();else if(w==2)search20();else if(w==3)index20(null,true);else if(w==4)diagnose20();else new AlertDialog.Builder(this).setTitle("Lokal analys").setMessage("Ansiktsmotorn är samma Alignment 6.0 som gav bra träffar. Personalbum sparas lokalt och ändrar inte originalbilderna.").setPositiveButton("OK",null).show();}).setNegativeButton("Stäng",null).show();}
 void createPersonAlbum21(){ArrayList<Item> refs=selectedItems();refs.removeIf(Item::video);if(refs.isEmpty()){Toast.makeText(this,"Markera 1–5 tydliga bilder av personen först",Toast.LENGTH_LONG).show();return;}if(refs.size()>5)refs=new ArrayList<>(refs.subList(0,5));final ArrayList<Item> rr=refs;EditText e=new EditText(this);e.setHint("Personens namn");e.setSingleLine(true);new AlertDialog.Builder(this).setTitle("➕ Nytt personalbum").setMessage("Ge personen ett namn. Smart Gallery använder de markerade bilderna som referenser.").setView(e).setPositiveButton("Skapa",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty()){Toast.makeText(this,"Skriv ett namn",Toast.LENGTH_LONG).show();return;}buildAlbum21(n,rr);}).setNegativeButton("Avbryt",null).show();}
 void buildAlbum21(String name,ArrayList<Item> refs){ProgressDialog pd=new ProgressDialog(this);pd.setTitle("👤 "+name);pd.setMessage("Matchar mot personindex…");pd.setCancelable(false);pd.show();pool.execute(()->{try{File cache=new File(getFilesDir(),"face-embeddings-v6-aligned.txt");HashMap<String,ArrayList<float[]>> idx=readEmb18(cache);if(idx.isEmpty())throw new Exception("Personindex 6.0 saknas. Bygg indexet först.");org.tensorflow.lite.Interpreter tf=new org.tensorflow.lite.Interpreter(loadModel18());com.google.mlkit.vision.face.FaceDetectorOptions o=new com.google.mlkit.vision.face.FaceDetectorOptions.Builder().setPerformanceMode(com.google.mlkit.vision.face.FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).setLandmarkMode(com.google.mlkit.vision.face.FaceDetectorOptions.LANDMARK_MODE_ALL).setMinFaceSize(.03f).build();com.google.mlkit.vision.face.FaceDetector det=com.google.mlkit.vision.face.FaceDetection.getClient(o);ArrayList<float[]> seeds=new ArrayList<>();for(Item r:refs){ArrayList<float[]> x=embeddings20(faceBitmap(r),det,tf);if(!x.isEmpty())seeds.add(x.get(0));}if(seeds.isEmpty())throw new Exception("Inget tydligt ansikte hittades i referenserna.");ArrayList<Map.Entry<String,Float>> rank=new ArrayList<>();for(Map.Entry<String,ArrayList<float[]>> en:idx.entrySet()){float best=-1;for(float[]x:en.getValue())for(float[]s:seeds)best=Math.max(best,cos18(x,s));rank.add(new AbstractMap.SimpleEntry<>(en.getKey(),best));}rank.sort((a,b)->Float.compare(b.getValue(),a.getValue()));ArrayList<String> uris=new ArrayList<>();for(Map.Entry<String,Float> q:rank)if(q.getValue()>=.35f&&uris.size()<500)uris.add(q.getKey());saveAlbum21(name,uris);det.close();tf.close();runOnUiThread(()->{pd.dismiss();Toast.makeText(this,name+" • "+uris.size()+" bilder",Toast.LENGTH_LONG).show();showPersonAlbums21();});}catch(Exception ex){runOnUiThread(()->{pd.dismiss();new AlertDialog.Builder(this).setTitle("Personalbum").setMessage(ex.getMessage()).setPositiveButton("OK",null).show();});}});}
 void saveAlbum21(String name,ArrayList<String> uris){getSharedPreferences(PA_PREF,MODE_PRIVATE).edit().putString(name,android.text.TextUtils.join("\n",uris)).apply();}
 LinkedHashMap<String,ArrayList<String>> albums21(){LinkedHashMap<String,ArrayList<String>> out=new LinkedHashMap<>();Map<String,?> m=getSharedPreferences(PA_PREF,MODE_PRIVATE).getAll();ArrayList<String> names=new ArrayList<>(m.keySet());Collections.sort(names,String.CASE_INSENSITIVE_ORDER);for(String n:names){String s=String.valueOf(m.get(n));ArrayList<String> u=new ArrayList<>();if(!s.isEmpty())u.addAll(Arrays.asList(s.split("\\n")));out.put(n,u);}return out;}
 void showPersonAlbums21(){LinkedHashMap<String,ArrayList<String>> m=albums21();if(m.isEmpty()){new AlertDialog.Builder(this).setTitle("🖼 Personalbum").setMessage("Inga personalbum ännu.\n\nMarkera några tydliga bilder av en person och välj ‘Skapa personalbum från markerade’.").setPositiveButton("OK",null).show();return;}String[] a=new String[m.size()];int k=0;for(Map.Entry<String,ArrayList<String>>e:m.entrySet())a[k++]=e.getKey()+"  •  "+e.getValue().size()+" bilder";ArrayList<String> names=new ArrayList<>(m.keySet());new AlertDialog.Builder(this).setTitle("🖼 Personalbum").setItems(a,(d,w)->openAlbum21(names.get(w),m.get(names.get(w)))).setNegativeButton("Stäng",null).show();}
 void openAlbum21(String name,ArrayList<String> uris){HashSet<String>s=new HashSet<>(uris);ArrayList<Item> r=new ArrayList<>();for(Item i:all)if(s.contains(i.uri.toString()))r.add(i);returnScreen=screen;screen=3;selectionMode=false;selected.clear();baseRoot();LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹");back.setTextSize(28);back.setOnClickListener(v->onBackPressed());h.addView(back,new LinearLayout.LayoutParams(dp(54),-2));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(tv(name,25,true));TextView sub=tv(r.size()+" bilder • Personalbum",13,false);sub.setTextColor(ACC);t.addView(sub);h.addView(t,new LinearLayout.LayoutParams(0,-2,1));root.addView(h);shown.clear();shown.addAll(r);grid=new GridView(this);grid.setNumColumns(3);grid.setHorizontalSpacing(dp(3));grid.setVerticalSpacing(dp(3));adapter=new SelectAdapter();grid.setAdapter(adapter);grid.setOnItemLongClickListener((p,v,pos,id)->{selectionMode=true;toggle(shown.get(pos));return true;});root.addView(grid,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
}
