package se.smartgallery.app;

import android.app.*;import android.graphics.*;import android.view.*;import android.widget.*;import com.google.android.gms.tasks.Tasks;import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.face.*;import org.tensorflow.lite.Interpreter;import java.io.*;import java.nio.*;import java.nio.channels.FileChannel;import java.util.*;import java.util.concurrent.TimeUnit;

public class MainActivity18 extends MainActivity17{
 static class E{String uri;float[]v;E(String u,float[]x){uri=u;v=x;}}
 @Override void peoplePage(){String[]a={"👤 Hitta samma person – Embedding 4.0","🧠 Bygg om personindex 4.0","🏷 Namnge person","🔒 Om analysen"};new AlertDialog.Builder(this).setTitle("👥 Personer 4.0").setMessage("1.8 använder en riktig neural ansikts-embedding lokalt på telefonen. Markera gärna 1–5 tydliga bilder av samma person.").setItems(a,(d,w)->{if(w==0)embedSearch18();else if(w==1)embedIndex18(null,true);else if(w==2)namePerson();else new AlertDialog.Builder(this).setTitle("Lokal ansiktsanalys").setMessage("Bilder lämnar inte telefonen. ML Kit hittar ansikten och den lokala embedding-modellen omvandlar varje ansikte till en numerisk vektor. Indexet sparas endast i appens privata lagring.").setPositiveButton("OK",null).show();}).setNegativeButton("Stäng",null).show();}
 void embedSearch18(){ArrayList<Item>refs=selectedItems();refs.removeIf(Item::video);if(refs.isEmpty()){Toast.makeText(this,"Markera minst en bild av personen",Toast.LENGTH_LONG).show();return;}if(refs.size()>5)refs=new ArrayList<>(refs.subList(0,5));embedIndex18(refs,false);}
 void embedIndex18(ArrayList<Item>refs,boolean rebuild){ProgressDialog pd=new ProgressDialog(this);pd.setTitle("🧠 Personer 4.0");pd.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);pd.setMax(all.size());pd.setCancelable(true);pd.setMessage("Startar neural ansiktsanalys…");pd.show();final ArrayList<Item>rr=refs;pool.execute(()->{Interpreter tf=null;FaceDetector det=null;try{tf=new Interpreter(loadModel18());FaceDetectorOptions o=new FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL).setMinFaceSize(.06f).build();det=FaceDetection.getClient(o);File cache=new File(getFilesDir(),"face-embeddings-v4.txt");HashMap<String,ArrayList<float[]>>idx=rebuild?new HashMap<>():readEmb18(cache);int n=0,fc=0;for(Item i:all){if(pd.isCancelled())break;n++;if(!i.video()&&!idx.containsKey(i.uri.toString())){try{ArrayList<float[]>es=embeddings18(faceBitmap(i),det,tf);idx.put(i.uri.toString(),es);fc+=es.size();}catch(Exception e){idx.put(i.uri.toString(),new ArrayList<>());}}if(n%8==0){final int z=n,fz=fc;runOnUiThread(()->{pd.setProgress(z);pd.setMessage("Analyserat "+z+" / "+all.size()+" • "+fz+" nya ansikten");});}}writeEmb18(cache,idx);if(rr==null){runOnUiThread(()->{pd.dismiss();Toast.makeText(this,"Personindex 4.0 klart • "+idx.size()+" bilder",Toast.LENGTH_LONG).show();});return;}ArrayList<float[]>seeds=new ArrayList<>();for(Item r:rr)try{seeds.addAll(embeddings18(faceBitmap(r),det,tf));}catch(Exception ignored){}if(seeds.isEmpty()){runOnUiThread(()->{pd.dismiss();Toast.makeText(this,"Inget tydligt ansikte hittades i referensbilderna",Toast.LENGTH_LONG).show();});return;}HashMap<String,Float>score=new HashMap<>();for(Map.Entry<String,ArrayList<float[]>>en:idx.entrySet()){float best=-1;for(float[]x:en.getValue())for(float[]s:seeds)best=Math.max(best,cos18(x,s));if(best>=.42f)score.put(en.getKey(),best);}ArrayList<Item>cand=new ArrayList<>();HashSet<String>seen=new HashSet<>();for(Item i:all)if(score.containsKey(i.uri.toString())&&seen.add(i.uri.toString()))cand.add(i);cand.sort((a,b)->Float.compare(score.get(b.uri.toString()),score.get(a.uri.toString())));int sure=0,possible=0,weak=0;for(Item i:cand){float s=score.get(i.uri.toString());if(s>=.67f)sure++;else if(s>=.54f)possible++;else weak++;}final int A=sure,B=possible,C=weak;runOnUiThread(()->{pd.dismiss();showAdaptiveResults(cand,A,B,C);});}catch(Exception e){final String m=e.getMessage();runOnUiThread(()->{pd.dismiss();new AlertDialog.Builder(this).setTitle("Personer 4.0").setMessage("Embedding-motorn kunde inte starta"+(m==null?"":"\n\n"+m)).setPositiveButton("OK",null).show();});}finally{if(det!=null)det.close();if(tf!=null)tf.close();}});}
 MappedByteBuffer loadModel18()throws Exception{android.content.res.AssetFileDescriptor fd=getAssets().openFd("mobilefacenet.tflite");FileInputStream in=new FileInputStream(fd.getFileDescriptor());MappedByteBuffer b=in.getChannel().map(FileChannel.MapMode.READ_ONLY,fd.getStartOffset(),fd.getDeclaredLength());in.close();fd.close();return b;}
 ArrayList<float[]> embeddings18(Bitmap b,FaceDetector d,Interpreter tf)throws Exception{ArrayList<float[]>out=new ArrayList<>();if(b==null)return out;List<Face>fs=Tasks.await(d.process(InputImage.fromBitmap(b,0)),30,TimeUnit.SECONDS);int[]shape=tf.getInputTensor(0).shape();int h=shape.length>2?shape[1]:112,w=shape.length>2?shape[2]:112;int od=1;int[]os=tf.getOutputTensor(0).shape();for(int x:os)od*=x;for(Face f:fs){Rect q=new Rect(f.getBoundingBox());int p=(int)(Math.max(q.width(),q.height())*.25f);q.left=Math.max(0,q.left-p);q.top=Math.max(0,q.top-p);q.right=Math.min(b.getWidth(),q.right+p);q.bottom=Math.min(b.getHeight(),q.bottom+p);if(q.width()<20||q.height()<20)continue;Bitmap c=Bitmap.createScaledBitmap(Bitmap.createBitmap(b,q.left,q.top,q.width(),q.height()),w,h,true);ByteBuffer input=ByteBuffer.allocateDirect(4*w*h*3).order(ByteOrder.nativeOrder());for(int y=0;y<h;y++)for(int x=0;x<w;x++){int z=c.getPixel(x,y);input.putFloat((Color.red(z)-127.5f)/128f);input.putFloat((Color.green(z)-127.5f)/128f);input.putFloat((Color.blue(z)-127.5f)/128f);}input.rewind();float[][]o=new float[1][od];tf.run(input,o);norm18(o[0]);out.add(o[0]);}return out;}
 void norm18(float[]v){double n=0;for(float x:v)n+=x*x;n=Math.sqrt(n)+1e-9;for(int i=0;i<v.length;i++)v[i]/=(float)n;}
 float cos18(float[]a,float[]b){if(a.length!=b.length)return-1;float s=0;for(int i=0;i<a.length;i++)s+=a[i]*b[i];return s;}
 HashMap<String,ArrayList<float[]>>readEmb18(File f){HashMap<String,ArrayList<float[]>>m=new HashMap<>();if(!f.exists())return m;try(BufferedReader r=new BufferedReader(new FileReader(f))){String l;while((l=r.readLine())!=null){String[]p=l.split("\\|",2);if(p.length<2)continue;ArrayList<float[]>a=new ArrayList<>();for(String e:p[1].split(";")){if(e.isEmpty())continue;String[]z=e.split(",");float[]v=new float[z.length];for(int i=0;i<z.length;i++)v[i]=Float.parseFloat(z[i]);a.add(v);}m.put(p[0],a);}}catch(Exception e){m.clear();}return m;}
 void writeEmb18(File f,HashMap<String,ArrayList<float[]>>m){try(BufferedWriter w=new BufferedWriter(new FileWriter(f))){for(Map.Entry<String,ArrayList<float[]>>e:m.entrySet()){w.write(e.getKey()+"|");boolean ff=true;for(float[]v:e.getValue()){if(!ff)w.write(";");ff=false;for(int i=0;i<v.length;i++){if(i>0)w.write(",");w.write(String.format(Locale.ROOT,"%.6f",v[i]));}}w.newLine();}}catch(Exception ignored){}}
}
