plugins { id 'com.android.application' }
android {
 namespace 'se.smartgallery.app'
 compileSdk 35
 defaultConfig { applicationId 'se.smartgallery.app'; minSdk 26; targetSdk 35; versionCode 14; versionName '1.4' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_11; targetCompatibility JavaVersion.VERSION_11 }
}
dependencies {
 implementation 'com.google.mlkit:face-detection:16.1.7'
}
